/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as HotelIndexRouteImport } from './routes/$hotel.index'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRoomsRouteImport } from './routes/dashboard.rooms'
import { Route as DashboardReservationsRouteImport } from './routes/dashboard.reservations'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPosRouteImport } from './routes/dashboard.pos'
import { Route as DashboardMaintenanceRouteImport } from './routes/dashboard.maintenance'
import { Route as DashboardHousekeepingRouteImport } from './routes/dashboard.housekeeping'
import { Route as DashboardGuestsRouteImport } from './routes/dashboard.guests'
import { Route as DashboardFrontDeskRouteImport } from './routes/dashboard.front-desk'
import { Route as DashboardChannelManagerRouteImport } from './routes/dashboard.channel-manager'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as HotelBookRouteImport } from './routes/$hotel.book'
import { Route as DashboardSettingsHotelRouteImport } from './routes/dashboard.settings.hotel'
import { Route as DashboardReservationsIdRouteImport } from './routes/dashboard.reservations.$id'
import { Route as DashboardGuestsIdRouteImport } from './routes/dashboard.guests.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const HotelIndexRoute = HotelIndexRouteImport.update({
  id: '/$hotel/',
  path: '/$hotel/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoomsRoute = DashboardRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReservationsRoute = DashboardReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPosRoute = DashboardPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHousekeepingRoute = DashboardHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuestsRoute = DashboardGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFrontDeskRoute = DashboardFrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChannelManagerRoute = DashboardChannelManagerRouteImport.update({
  id: '/channel-manager',
  path: '/channel-manager',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookRoute = HotelBookRouteImport.update({
  id: '/$hotel/book',
  path: '/$hotel/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsHotelRoute = DashboardSettingsHotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardReservationsIdRoute = DashboardReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardReservationsRoute,
} as any)
const DashboardGuestsIdRoute = DashboardGuestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardGuestsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/login': typeof LoginRoute
  '/$hotel/book': typeof HotelBookRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/channel-manager': typeof DashboardChannelManagerRoute
  '/dashboard/front-desk': typeof DashboardFrontDeskRoute
  '/dashboard/guests': typeof DashboardGuestsRouteWithChildren
  '/dashboard/housekeeping': typeof DashboardHousekeepingRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reservations': typeof DashboardReservationsRouteWithChildren
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRoute
  '/$hotel/': typeof HotelIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/guests/$id': typeof DashboardGuestsIdRoute
  '/dashboard/reservations/$id': typeof DashboardReservationsIdRoute
  '/dashboard/settings/hotel': typeof DashboardSettingsHotelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/login': typeof LoginRoute
  '/$hotel/book': typeof HotelBookRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/channel-manager': typeof DashboardChannelManagerRoute
  '/dashboard/front-desk': typeof DashboardFrontDeskRoute
  '/dashboard/guests': typeof DashboardGuestsRouteWithChildren
  '/dashboard/housekeeping': typeof DashboardHousekeepingRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reservations': typeof DashboardReservationsRouteWithChildren
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRoute
  '/$hotel': typeof HotelIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/guests/$id': typeof DashboardGuestsIdRoute
  '/dashboard/reservations/$id': typeof DashboardReservationsIdRoute
  '/dashboard/settings/hotel': typeof DashboardSettingsHotelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/login': typeof LoginRoute
  '/$hotel/book': typeof HotelBookRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/channel-manager': typeof DashboardChannelManagerRoute
  '/dashboard/front-desk': typeof DashboardFrontDeskRoute
  '/dashboard/guests': typeof DashboardGuestsRouteWithChildren
  '/dashboard/housekeeping': typeof DashboardHousekeepingRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reservations': typeof DashboardReservationsRouteWithChildren
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRoute
  '/$hotel/': typeof HotelIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/guests/$id': typeof DashboardGuestsIdRoute
  '/dashboard/reservations/$id': typeof DashboardReservationsIdRoute
  '/dashboard/settings/hotel': typeof DashboardSettingsHotelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favicon.ico'
    | '/login'
    | '/$hotel/book'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/channel-manager'
    | '/dashboard/front-desk'
    | '/dashboard/guests'
    | '/dashboard/housekeeping'
    | '/dashboard/maintenance'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/reservations'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/$hotel/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/guests/$id'
    | '/dashboard/reservations/$id'
    | '/dashboard/settings/hotel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favicon.ico'
    | '/login'
    | '/$hotel/book'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/channel-manager'
    | '/dashboard/front-desk'
    | '/dashboard/guests'
    | '/dashboard/housekeeping'
    | '/dashboard/maintenance'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/reservations'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/$hotel'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/guests/$id'
    | '/dashboard/reservations/$id'
    | '/dashboard/settings/hotel'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/favicon.ico'
    | '/login'
    | '/$hotel/book'
    | '/api/health'
    | '/dashboard/billing'
    | '/dashboard/channel-manager'
    | '/dashboard/front-desk'
    | '/dashboard/guests'
    | '/dashboard/housekeeping'
    | '/dashboard/maintenance'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/reservations'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/$hotel/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/guests/$id'
    | '/dashboard/reservations/$id'
    | '/dashboard/settings/hotel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  LoginRoute: typeof LoginRoute
  HotelBookRoute: typeof HotelBookRoute
  ApiHealthRoute: typeof ApiHealthRoute
  HotelIndexRoute: typeof HotelIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/$hotel/': {
      id: '/$hotel/'
      path: '/$hotel'
      fullPath: '/$hotel/'
      preLoaderRoute: typeof HotelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rooms': {
      id: '/dashboard/rooms'
      path: '/rooms'
      fullPath: '/dashboard/rooms'
      preLoaderRoute: typeof DashboardRoomsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reservations': {
      id: '/dashboard/reservations'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof DashboardReservationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pos': {
      id: '/dashboard/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof DashboardPosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maintenance': {
      id: '/dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/dashboard/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/housekeeping': {
      id: '/dashboard/housekeeping'
      path: '/housekeeping'
      fullPath: '/dashboard/housekeeping'
      preLoaderRoute: typeof DashboardHousekeepingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guests': {
      id: '/dashboard/guests'
      path: '/guests'
      fullPath: '/dashboard/guests'
      preLoaderRoute: typeof DashboardGuestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/front-desk': {
      id: '/dashboard/front-desk'
      path: '/front-desk'
      fullPath: '/dashboard/front-desk'
      preLoaderRoute: typeof DashboardFrontDeskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/channel-manager': {
      id: '/dashboard/channel-manager'
      path: '/channel-manager'
      fullPath: '/dashboard/channel-manager'
      preLoaderRoute: typeof DashboardChannelManagerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$hotel/book': {
      id: '/$hotel/book'
      path: '/$hotel/book'
      fullPath: '/$hotel/book'
      preLoaderRoute: typeof HotelBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/hotel': {
      id: '/dashboard/settings/hotel'
      path: '/hotel'
      fullPath: '/dashboard/settings/hotel'
      preLoaderRoute: typeof DashboardSettingsHotelRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/reservations/$id': {
      id: '/dashboard/reservations/$id'
      path: '/$id'
      fullPath: '/dashboard/reservations/$id'
      preLoaderRoute: typeof DashboardReservationsIdRouteImport
      parentRoute: typeof DashboardReservationsRoute
    }
    '/dashboard/guests/$id': {
      id: '/dashboard/guests/$id'
      path: '/$id'
      fullPath: '/dashboard/guests/$id'
      preLoaderRoute: typeof DashboardGuestsIdRouteImport
      parentRoute: typeof DashboardGuestsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardGuestsRouteChildren {
  DashboardGuestsIdRoute: typeof DashboardGuestsIdRoute
}

const DashboardGuestsRouteChildren: DashboardGuestsRouteChildren = {
  DashboardGuestsIdRoute: DashboardGuestsIdRoute,
}

const DashboardGuestsRouteWithChildren = DashboardGuestsRoute._addFileChildren(
  DashboardGuestsRouteChildren,
)

interface DashboardReservationsRouteChildren {
  DashboardReservationsIdRoute: typeof DashboardReservationsIdRoute
}

const DashboardReservationsRouteChildren: DashboardReservationsRouteChildren = {
  DashboardReservationsIdRoute: DashboardReservationsIdRoute,
}

const DashboardReservationsRouteWithChildren =
  DashboardReservationsRoute._addFileChildren(
    DashboardReservationsRouteChildren,
  )

interface DashboardSettingsRouteChildren {
  DashboardSettingsHotelRoute: typeof DashboardSettingsHotelRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsHotelRoute: DashboardSettingsHotelRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardChannelManagerRoute: typeof DashboardChannelManagerRoute
  DashboardFrontDeskRoute: typeof DashboardFrontDeskRoute
  DashboardGuestsRoute: typeof DashboardGuestsRouteWithChildren
  DashboardHousekeepingRoute: typeof DashboardHousekeepingRoute
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRoute
  DashboardPosRoute: typeof DashboardPosRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReservationsRoute: typeof DashboardReservationsRouteWithChildren
  DashboardRoomsRoute: typeof DashboardRoomsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardChannelManagerRoute: DashboardChannelManagerRoute,
  DashboardFrontDeskRoute: DashboardFrontDeskRoute,
  DashboardGuestsRoute: DashboardGuestsRouteWithChildren,
  DashboardHousekeepingRoute: DashboardHousekeepingRoute,
  DashboardMaintenanceRoute: DashboardMaintenanceRoute,
  DashboardPosRoute: DashboardPosRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReservationsRoute: DashboardReservationsRouteWithChildren,
  DashboardRoomsRoute: DashboardRoomsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaviconDoticoRoute: FaviconDoticoRoute,
  LoginRoute: LoginRoute,
  HotelBookRoute: HotelBookRoute,
  ApiHealthRoute: ApiHealthRoute,
  HotelIndexRoute: HotelIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
